import Head from 'next/head'
import Register from '../components/register'
import Sidebar from '../components/Sidebar'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-gray-900 text-white px-8">
      <Head>
        <title>VentureLabs Test App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col py-16 px-0 justify-center items-center min-h-screen">
        <Sidebar />

        <Register />
        <img loading="lazy" width="648" height="65" src="https://venturelabs.group/wp-content/uploads/2021/08/logoVenturelabs.png" alt="Logo Venture Labs" title="logoVenturelabs" />
        <img loading="lazy" width="400" height="300" src="https://venturelabs.group/wp-content/uploads/2021/08/VL_Element.gif" alt="" title="VL_Element" />
        <h1 className={styles.title}>
          Test App!
        </h1>
      </main>

      <Footer />
    </div>
  )
}
